version: "3.4"

x-app: &app
  image: freeconsultant-jp-dev
  user: "ruby:ruby"
  env_file:
    - .env
  volumes:
    - .:/app:cached
    - app-tmp-cache:/app/tmp/cache
    - bundle_v30:/usr/local/bundle
    - yarn-cache:/home/ruby/.cache/yarn
    - node_modules18:/app/node_modules
    - ~/.netrc:/home/ruby/.netrc
  tty: true
  stdin_open: true

services:
  app:
    <<: *app
    build: .
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    entrypoint:
      - "prehook"
      - "ruby -v"
      - "bundle install"
      - "rm -f tmp/pids/server.pid"
      - "--"
    environment:
      REDIS_URL: redis://redis:6379
      HOSTS_WHITELIST: ${HOSTS_WHITELIST-""}
      BLAZER_DATABASE_URL: postgres://postgres:password@db:5432/app_development
      VIRTUAL_HOST: fcweb.ruffnote-dev.com
    ports:
      - 3000:3000
    depends_on:
      - db
  worker:
    <<: *app
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    entrypoint:
      - "prehook"
      - "ruby -v"
      - "dockerize --wait file:///app/tmp/pids/server.pid -timeout 60s"
      - "--"
    environment:
      REDIS_URL: redis://redis:6379
      BLAZER_DATABASE_URL: postgres://postgres:password@db:5432/app_development
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy
  assets:
    <<: *app
    command: ["bin/dev"]
    entrypoint:
      - "prehook"
      - "yarn install --check-files"
      - "--"
  db:
    image: postgres:12
    volumes:
      - pg_data_12:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:5.0.8
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 30s
      retries: 30
  wpdb:
    image: mysql/mysql-server:5.7
    volumes:
      - wpdb_data:/var/lib/mysql
      - ./tmp:/app_tmp:cached
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: root
      MYSQL_DATABASE: wp_development
      MYSQL_ROOT_HOST: '%'
  chrome:
    image: seleniarm/standalone-chromium:114.0
    shm_size: 512m
  web:
    image: nginxproxy/nginx-proxy:1.3.1
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - 443:443

volumes:
  pg_data_12:
    driver: local
  bundle_v30:
    driver: local
  yarn-cache:
    driver: local
  app-tmp-cache:
    driver: local
  redis_data:
    driver: local
  wpdb_data:
    driver: local
  node_modules18:
    driver: local
