---
default: &default
  cloud_name: <%= Rails.application.credentials.dig(:cloudinary, :cloud_name) %>
  api_key: <%= Rails.application.credentials.dig(:cloudinary, :api_key) %>
  api_secret: <%= Rails.application.credentials.dig(:cloudinary, :api_secret) %>
  secure: true
  enhance_image_tag: true
  static_file_support: false

development:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

review:
  <<: *default

test:
  <<: *default
