default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

wordpress:
  adapter: mysql2
  host: <%= ENV.fetch('WP_DB_HOST') { Rails.application.credentials.wordpress[:host] } %>
  database: <%= ENV.fetch('WP_DB_DATABASE') { Rails.application.credentials.wordpress[:database] } %>
  username: <%= ENV.fetch('WP_DB_USERNAME') { Rails.application.credentials.wordpress[:username] } %>
  password: <%= ENV.fetch('WP_DB_PASSWORD') { Rails.application.credentials.wordpress[:password] } %>
  encoding: utf8mb4

development: &development
  <<: *default
  database: app_development
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWPRD") { 'password' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'db' } %>

test:
  <<: *development
  database: freeconsultant_test
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'password' } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'db' } %>
  # schema_search_path: "public,salesforce"

staging:
  <<: *default

review:
  <<: *default

production:
  <<: *default
