default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: app_development
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWPRD") { 'password' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'db' } %>
  schema_search_path: "salesforce"

test:
  <<: *development
  database: freeconsultant_test
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'password' } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'db' } %>
  url: <%= ENV['DATABASE_URL'] %>
  schema_search_path: "salesforce"
